### ISSUE TITLE
WINDOWS_2016_SQL_SERVER_STANDARD_2016 and WINDOWS_2016_SQL_SERVER_ENTERPRISE_2016 keywords no longer work.

### ISSUE THREAD

**Issue by jg-par** [awsdocs/aws-powershell-user-guide#19]
The keywords WINDOWS_2016_SQL_SERVER_STANDARD_2016 and WINDOWS_2016_SQL_SERVER_ENTERPRISE_2016 no longer work in the Get-Ec2ImageByName cmdlet. When I try the command returns an error "Get-EC2ImageByName : Sequence contains no elements"

Has this has been deprecated/replaced or is it an error in the API?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
